config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/index'
  get 'home/about'
  
  resources :clients
  resources :grupo_recursos
  get 'tabela_compras/planilha'
  post 'tabela_compras/newPlanilha'
  resources :tabela_compras
  resources :recursos
  resources :suppliers
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/grupo_recurso.rb
# == Schema Information
#
# Table name: grupo_recursos
#
#  id         :bigint           not null, primary key
#  nome       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class GrupoRecurso < ApplicationRecord
    has_many :recursos
    validates_presence_of :nome

    before_save :formata

    private
    def formata
        self.nome = self.nome.split.collect(&:capitalize).join(' ') if self.nome && !self.nome.blank?
    end 
end

app/controllers/grupo_recursos_controller.rb
class GrupoRecursosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_grupo_recurso, only: %i[ show edit update destroy ]

  # GET /grupo_recursos or /grupo_recursos.json
  def index
    @grupo_recursos = GrupoRecurso.all
  end

  # GET /grupo_recursos/1 or /grupo_recursos/1.json
  def show
  end

  # GET /grupo_recursos/new
  def new
    @grupo_recurso = GrupoRecurso.new
  end

  # GET /grupo_recursos/1/edit
  def edit
  end

  # POST /grupo_recursos or /grupo_recursos.json
  def create
    @grupo_recurso = GrupoRecurso.new(grupo_recurso_params)

    respond_to do |format|
      if @grupo_recurso.save
        format.html { redirect_to grupo_recurso_url(@grupo_recurso), notice: "Grupo de recurso foi gravado com sucesso." }
        format.json { render :show, status: :created, location: @grupo_recurso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grupo_recurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupo_recursos/1 or /grupo_recursos/1.json
  def update
    respond_to do |format|
      if @grupo_recurso.update(grupo_recurso_params)
        format.html { redirect_to grupo_recurso_url(@grupo_recurso), notice: "Grupo de recurso foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @grupo_recurso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grupo_recurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupo_recursos/1 or /grupo_recursos/1.json
  def destroy
    @grupo_recurso.destroy

    respond_to do |format|
      format.html { redirect_to grupo_recursos_url, notice: "Grupo de Recurso foi excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo_recurso
      @grupo_recurso = GrupoRecurso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grupo_recurso_params
      params.require(:grupo_recurso).permit(:nome)
    end
end

app/helpers/grupo_recursos_helper.rb
module GrupoRecursosHelper
end

app/views/grupo_recursos/_form.html.erb
<div class="form-body">
  <div class="row">
      <div class="form-holder">
        <div class="form-content">
          <div class="form-items">
            <h3 class="form-title"> Grupo de Recurso </h3>

<%= form_with(model: grupo_recurso) do |form| %>
  <% if grupo_recurso.errors.any? %>
    <div style="color: red">
      <h2><%= grupo_recurso.errors.count %> <%= grupo_recurso.errors.count==1 ? "erro deve" : "erros devem" %> ser corrigidos:</h2>

      <ul>
        <% grupo_recurso.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-1 mb-0">
    <%= form.label :nome, style: "display: block", class: "form-label" %>
    <%= form.text_field :nome, size: 50, class: "form-control", placeholder: "Nome do Grupo de Recurso"  %>
  </div>
  
  <div class="row" style="border-top: 4px;">
    <%= form.submit  class: "btn btn-primary col-md-4 offset-md-4"  %>
  </div>
  
<% end %>
</div>
      </div>
    </div>
  </div>
</div>

app/views/grupo_recursos/_grupo_recurso.html.erb
<div id="<%= dom_id grupo_recurso %>">
  <p>
    <strong>Nome:</strong>
    <%= grupo_recurso.nome %>
  </p>

</div>

app/views/grupo_recursos/edit.html.erb
<%= render "form", grupo_recurso: @grupo_recurso %>
<br>

<div class="col-12">
  <%= link_to "Mostrar Grupo de Recurso", @grupo_recurso, class: "btn btn-secondary"  %> |
  <%= link_to "Lista de Grupo de Recursos", grupo_recursos_path, class: "btn btn-secondary"  %>
</div>

app/views/grupo_recursos/index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

<div class="flex">
  <h1 class="text-black">Grupo de Recursos</h1>
  <%= link_to "+ Novo Grupo de Recurso", new_grupo_recurso_path, class: "btn btn-info small" %>
</div>
<br>
<div id="tabGrupo_recursos" style="width: 98%;">
  <table id="grupo_recursos" class="table dataTable datatable-basic table-striped table-bordered table-hover display bg-gray" 
  role="grid">
  <thead>
    <th>Nome</th>
    <th></th>
  </thead>
  <tbody>
    <% @grupo_recursos.each do |grupo_recurso| %>
      <tr>
        <td><%= grupo_recurso.nome %></td>
        <td> <%= link_to "Detalhes", grupo_recurso, class: "btn btn-secondary" %> </td>
      </tr>
    <% end %>
  </tbody>
</div>


<script>
  $(document).ready(function(){
     $('#grupo_recursos').DataTable({
        autoWidth: true,
        info: false,
        searching: true,
        order: [[1]],
        paging: false,
        "language": {
          "url": "//cdn.datatables.net/plug-ins/1.11.3/i18n/pt_br.json"
        }
     });
  });
</script>

app/views/grupo_recursos/new.html.erb
<div>
    <%= link_to "Lista de Grupo de Recursos", grupo_recursos_path, class: "btn btn-secondary" %>
</div>

<%= render "form", grupo_recurso: @grupo_recurso %>
<br>

app/views/grupo_recursos/show.html.erb
<div id="detalhe" class="text-black">
  <h3>Grupo de Recurso</h3>
  <%= render @grupo_recurso %>
</div>

<div class="btn-group" role="group" style="display: inline-block;">
  <%= link_to "Editar Grupo de Recurso", edit_grupo_recurso_path(@grupo_recurso), class: "btn btn-info" %> |
  <%= link_to "Listar Grupo de Recursos", grupo_recursos_path, class: "btn btn-secondary" %>|
  <%= button_to "Apagar este Grupo de Recurso", @grupo_recurso, method: :delete, class: "btn btn-danger inline " %>
</div>