config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/index'
  get 'home/about'
  
  resources :clients
  resources :grupo_recursos
  get 'tabela_compras/planilha'
  post 'tabela_compras/newPlanilha'
  resources :tabela_compras
  resources :recursos
  resources :suppliers
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/client.rb
class Client < Supplier
    after_initialize :set_defaults, unless: :persisted?

    def set_defaults
        self.type  ||= 'Client'
        self.estado ||='SP'
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Cliente gravado com sucesso." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Cliente atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Cliente excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:fantasia, :razaosocial, :telefone, :endereco, :cidade, :estado, :email, :whatsapp, :site, :ativo, :cnpj, :cpf)
    end
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Nome de Fantasia:</strong>
    <%= client.fantasia %>
  </p>

  <p>
    <strong>Razao Social:</strong>
    <%= client.razaosocial %>
  </p>

  <p>
    <strong>CNPJ:</strong>
    <%= client.cnpj %>
  </p>
  <p>
    <strong>CPF:</strong>
    <%= client.cpf %>
  </p>
  <p>
    <strong>Inscrição Estadual:</strong>
    <%= client.inscEstadual %>
  </p>
  <p>
    <strong>Telefone:</strong>
    <%= client.telefone %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= client.endereco %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= client.cidade %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= client.estado %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

  <p>
    <strong>Whatsapp:</strong>
    <%= client.whatsapp %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= client.instagram %>
  </p>

  <p>
    <strong>Site:</strong>
    <%= client.site %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= client.ativo %>
  </p>

</div>

app/views/clients/_form.html.erb
<div class="form-body">
  <div class="row">
      <div class="form-holder">
        <div class="form-content">
          <div class="form-items">
            <h3 class="form-title"> Cliente </h3>

<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= client.errors.count %> <%= client.errors.count==1 ? "erro" : "erros" %> devem ser corrigidos:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mt-1 mb-0">
    <%= form.label :fantasia,"Nome de Fantasia", style: "display: block", class: "form-label"%>
    <%= form.text_field :fantasia, size: 50, class: "form-control", placeholder: "Nome de Fantasia"  %>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :razaosocial, style: "display: block", class: "form-label" %>
    <%= form.text_field :razaosocial,  class: "form-control", placeholder: "Razao Social" %>
  </div>

  <div class="mt-1 mb-0 row">
    <div class="col-4">
      <%= form.label :cnpj, style: "display: block", class: "form-label" %>
      <%= form.text_field :cnpj,  class: "form-control", placeholder: "xx.xxx.xxx/xxxx-xx" %>
    </div>
    <div class="col">
      <%= form.label :inscEstadual, "Insc. Estadual", style: "display: block", class: "form-label" %>
      <%= form.text_field :inscEstadual,  class: "form-control", placeholder: ""  %>
    </div>
    <div class="col">
      <%= form.label :cpf, style: "display: block", class: "form-label" %>
      <%= form.text_field :cpf,  class: "form-control", placeholder: "xxx.xxx.xxx-xx"  %>
    </div>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :endereco, "Endereço", style: "display: block", class: "form-label" %>
    <%= form.text_field :endereco,  class: "form-control", placeholder: "Endereço" %>
  </div>

  <div class="mt-1 mb-0 row">
    <div class="col-9">
      <%= form.label :cidade, style: "display: block", class: "form-label" %>
      <%= form.text_field :cidade,  class: "form-control", placeholder: "Cidade" %>
    </div>
    <div class="col">
      <%= form.label :estado, style: "display: block", class: "form-label" %>
      <%= form.text_field :estado,  class: "form-control", placeholder: "UF"  %>
    </div>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :email, style: "display: block", class: "form-label" %>
    <%= form.text_field :email,  class: "form-control", placeholder: "email@email" %>
  </div>

  <div class="mt-1 mb-0 row">
    <div class="col-4">
      <%= form.label :telefone, style: "display: block", class: "form-label" %>
      <%= form.text_field :telefone,  class: "form-control", placeholder: "Telefone +55(XX) XXXXX-XXXX" %>
    </div>

    <div class="col">
      <%= form.label :whatsapp, style: "display: block", class: "form-label" %>
      <%= form.text_field :whatsapp,  class: "form-control", placeholder: "Telefone +55(XX) XXXXX-XXXX" %>
    </div>

    <div class="col">
      <%= form.label :instagram, "Instagram", style: "display: block", class: "form-label" %>
      <%= form.text_field :instagram,  class: "form-control", placeholder: "Instagram" %>
    </div>
  </div>
  <div class="mt-1 mb-0">
    <%= form.label :site, style: "display: block", class: "form-label" %>
    <%= form.text_field :site,  class: "form-control", placeholder: "http://site-da-empresa" %>
  </div>

  <div class="mt-1 mb-3">
    <%= form.check_box :ativo %>
    <%= form.label :ativo, style: "display: inline", class: "form-label" %>
  </div>

  <div class="row" style="border-top: 4px;">
    <%= button_tag "Limpar", type: :reset , class: "btn btn-secondary col-md-4 " %>
    <%= form.submit  class: "btn btn-primary col-md-4 offset-md-4"  %>
  </div>
<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/edit.html.erb
<%= render "form", client: @client %>
<br>

<div class="col-12">
  <%= link_to "Detalhes do Cliente", @client, class: "btn btn-secondary" %> |
  <%= link_to "Lista de Clientes", clients_path, class: "btn btn-secondary" %>
</div>

app/views/clients/index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

<div class="flex">
  <h1 class="text-black">Cliente</h1>
  <%= link_to "+ Novo Cliente", new_client_path, class: "btn btn-info small" %>
</div>
<br>
<div id="tabSuppliers" style="width: 98%;">
  <table id="clients" class="table dataTable datatable-basic table-striped table-bordered table-hover display bg-gray" 
  role="grid">
  <thead>
    <th>Nome Fantasia</th>
    <th>Razao Social</th>
    <th>CNPJ</th>
    <th>CPF</th>
    <th>Endereco<br>Cidade - Estado </th>
    <th>Contato</th>
    <th></th>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.fantasia %></td>
        <td><%= client.razaosocial %></td>
        <td><%= client.cnpj %></td>
        <td><%= client.cpf %></td>
        <td><%= client.endereco %><br><%= client.cidade %>-<%= client.estado %></td>
        <td><%= client.telefone %><br><%= client.whatsapp %></td>
        <td> <%= link_to "Detalhes", client, class: "btn btn-secondary" %> </td>
      </tr>
    <% end %>
  </tbody>
</div>


<script>
  $(document).ready(function(){
     $('#clients').DataTable({
        autoWidth: true,
        info: false,
        searching: true,
        order: [[1]],
        paging: false,
        "language": {
          "url": "//cdn.datatables.net/plug-ins/1.11.3/i18n/pt_br.json"
        }
     });
  });
</script>

app/views/clients/new.html.erb
<div>
    <%= link_to "Lista de Clientes", clients_path, class: "btn btn-secondary" %>
</div>

  <%= render "form", client: @client %>
  <br>

  

app/views/clients/show.html.erb
<div id="detalhe" class="text-black">
<h3>Cliente</h3>
<%= render @client %>
</div>

<div>
  <%= link_to "Editar Cliente", edit_client_path(@client), class: "btn btn-info" %> |
  <%= link_to "Listar Clientes", clients_path, class: "btn btn-secondary" %>|
  <%= button_to "Apagar este Cliente", @client, method: :delete, class: "btn btn-danger" %>
</div>