config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/index'
  get 'home/about'
  
  resources :clients
  resources :grupo_recursos
  get 'tabela_compras/planilha'
  post 'tabela_compras/newPlanilha'
  resources :tabela_compras
  resources :recursos
  resources :suppliers
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/tabela_compra.rb
# == Schema Information
#
# Table name: tabela_compras
#
#  id          :bigint           not null, primary key
#  data        :date
#  recurso_id  :bigint           not null
#  supplier_id :bigint           not null
#  valor       :decimal(, )
#  ativo       :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class TabelaCompra < ApplicationRecord
  belongs_to :recurso
  belongs_to :supplier
  
  validates_presence_of :supplier_id, :recurso_id, :valor 
  validates :valor, :numericality => {:only_integer => false}

  def self.savePlanilha(planilha)
    puts "Planilha: #{planilha}"
    res = Array.new
    res[0] = planilha[:data]
    res[1] = planilha[:supplier_id]

    planilha['recursos'].each do |single|
      res[2] = single['recurso_id']
      if (single['valor'].to_f > 0)
        insert = TabelaCompra.find_or_initialize_by(data: res[0], supplier_id: res[1], recurso_id: res[2])
        #debugger
        insert.valor = single['valor']
        insert.ativo = true
        insert.save!
      end
    end

    #Cria transação
    #Commit em loop

    return true
  end

end

app/controllers/tabela_compras_controller.rb
class TabelaComprasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tabela_compra, only: %i[ show edit update destroy ]

  # GET /tabela_compras or /tabela_compras.json
  def index
    @tabela_compras = TabelaCompra.all
  end

  # GET /tabela_compras/1 or /tabela_compras/1.json
  def show
  end

  # GET /tabela_compras/new
  def new
    @tabela_compra = TabelaCompra.new
  end

  def planilha
    @tabela_compra = TabelaCompra.new
    @recurso = Recurso.where(ativo: true).order(:nome)
  end

  def newPlanilha
    respond_to do |format|
      if @tabela_compra = TabelaCompra.savePlanilha(tabela_compra_params)
        format.html { redirect_to tabela_compras_url, notice: "Planilha criada com sucesso." }
      else
        puts "Params: #{params}"
        format.html { render :planilha, status: :unprocessable_entity }
      end
    end
  end

  # GET /tabela_compras/1/edit
  def edit
  end

  # POST /tabela_compras or /tabela_compras.json
  def create
    @tabela_compra = TabelaCompra.new(tabela_compra_params)
    respond_to do |format|
      if @tabela_compra.save
        format.html { redirect_to tabela_compra_url(@tabela_compra), notice: "Tabela de compra criada." }
        format.json { render :show, status: :created, location: @tabela_compra }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tabela_compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tabela_compras/1 or /tabela_compras/1.json
  def update
    respond_to do |format|
      if @tabela_compra.update(tabela_compra_params)
        format.html { redirect_to tabela_compra_url(@tabela_compra), notice: "Tabela de compra atualizada." }
        format.json { render :show, status: :ok, location: @tabela_compra }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tabela_compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tabela_compras/1 or /tabela_compras/1.json
  def destroy
    @tabela_compra.destroy

    respond_to do |format|
      format.html { redirect_to tabela_compras_url, notice: "Tabela de compra apagada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tabela_compra
      @tabela_compra = TabelaCompra.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tabela_compra_params
      params.require(:tabela_compra).permit(:data, :recurso_id, :supplier_id, :valor, :ativo, recursos: [:valor, :recurso_id])
    end
end

app/helpers/tabela_compras_helper.rb
module TabelaComprasHelper
end

app/views/tabela_compras/_form.html.erb
<div class="form-body">
  <div class="row">
      <div class="form-holder">
        <div class="form-content">
          <div class="form-items">
            <h3 class="form-title"> Preço do Fornecedor </h3>

<%= form_with(model: tabela_compra) do |form| %>
  <% if tabela_compra.errors.any? %>
    <div style="color: red">
      <h2><%= tabela_compra.errors.count %> <%= tabela_compra.errors.count==1 ? "erro deve" : "erros devem" %> ser corrigidos:</h2>

      <ul>
        <% tabela_compra.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-1 mb-0">
    <%= form.label :data, style: "display: block", style: "display: block", class: "form-label" %>
    <%= form.date_field :data, class: "form-control", placeholder: "Data da tabela" %>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :recurso_id, "Recurso", style: "display: block", class: "form-label"  %>
    <%= form.select :recurso_id, options_from_collection_for_select(Recurso.order(:nome), "id", "recurso_grupo", tabela_compra.recurso_id) %>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :supplier_id, "Fornecedor", style: "display: block", class: "form-label"  %>
    <%= form.select :supplier_id, options_from_collection_for_select(Supplier.order(:fantasia), "id", "nomesupplier", tabela_compra.supplier_id) %>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :valor, style: "display: block", style: "display: block", class: "form-label" %>
    <%= form.text_field :valor, class: "form-control", placeholder: "Valor" %>
  </div>

  <div class="mt-1 mb-3">
    <%= form.check_box :ativo %>
    <%= form.label :ativo, style: "display: inline", class: "form-label" %>
  </div>
  

  <div class="row" style="border-top: 4px;">
    <%= button_tag "Limpar", type: :reset , class: "btn btn-secondary col-md-4 " %>
    <%= form.submit  class: "btn btn-primary col-md-4 offset-md-4"  %>
  </div>
  
<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tabela_compras/_form_planilha.html.erb
<div class="form-body">
  <div class="row">
      <div class="form-holder">
        <div class="form-content">
          <div class="form-items">
            <h3 class="form-title"> Preço do Fornecedor </h3>

<%= form_with(model: tabela_compra, url: '/tabela_compras/newPlanilha') do |form| %>
  <% if tabela_compra.errors.any? %>
    <div style="color: red">
      <h2><%= tabela_compra.errors.count %> <%= tabela_compra.errors.count==1 ? "erro deve" : "erros devem" %> ser corrigidos:</h2>

      <ul>
        <% tabela_compra.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<div class="mt-1 mb-0">
   	<%= form.label :data, style: "display: block", style: "display: block", class: "form-label" %>
   	<%= form.date_field :data, class: "form-control", placeholder: "Data da tabela" , value: Time.now.strftime('%Y-%m-%d'), required: true %>
  </div>
	
  <div class="mt-1 mb-0">
   	<%= form.label :supplier_id, "Fornecedor", style: "display: block", class: "form-label"  %>
   	<%= form.select :supplier_id, options_from_collection_for_select(Supplier.order(:fantasia), "id", "nomesupplier", tabela_compra.supplier_id) %>
  </div>
	
  <% @recurso.each do |recurso| %>
    
       <div class="mt-1 mb-0"> 
        <%= form.hidden_field :recurso_id, name: 'tabela_compra[recursos[]recurso_id]' , value: recurso[:id] %>
        
        <%= form.label :valor, style: "display: block", style: "display: block", class: "form-label", value: recurso.nome %>
        <%= form.text_field :valor, name: 'tabela_compra[recursos[]valor]',class: "form-control float", placeholder: "Valor R$ 00,00" %>
      </div> 
    
  <% end %>
	 
	<br>
  	<div class="row" style="border-top: 4px;">
   	<%= button_tag "Limpar", type: :reset , class: "btn btn-secondary col-md-4 " %>
    	<%= form.submit  class: "btn btn-primary col-md-4 offset-md-4"  %>
  	</div>
<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tabela_compras/_tabela_compra.html.erb
<div id="<%= dom_id tabela_compra %>">
  <p>
    <strong>Data:</strong>
    <%= tabela_compra.data.strftime('%d/%m/%Y') %>
  </p>

  <p>
    <strong>Recurso:</strong>
    <%= tabela_compra.recurso.nome %>
  </p>

  <p>
    <strong>Supplier:</strong>
    <%= tabela_compra.supplier.fantasia %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= number_to_currency(tabela_compra.valor) %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= tabela_compra.ativo == true ? "SIM" : "NÃO" %>
  </p>

</div>

app/views/tabela_compras/edit.html.erb
<h1>Editing tabela compra</h1>

<%= render "form", tabela_compra: @tabela_compra %>

<br>

<div>
  <%= link_to "Show this tabela compra", @tabela_compra %> |
  <%= link_to "Back to tabela compras", tabela_compras_path %>
</div>

app/views/tabela_compras/index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

<div class="flex">
  <h1 class="text-black">Preço do Fornecedor</h1>
  <%= link_to "+ Novo Preço do Fornecedor", new_tabela_compra_path, class: "btn btn-info small" %>
  <%= link_to "+ Nova Planilha do Fornecedor", tabela_compras_planilha_path, class: "btn btn-info small" %>
</div>
<br>
<div id="tabTabCompras" style="width: 98%;">
  <table id="tabela_compras" class="table dataTable datatable-basic table-striped table-bordered table-hover display bg-gray" 
  role="grid">
  <thead>
    <th>Data</th>
    <th>Recurso</th>
    <th>Fornecedor</th>
    <th>Valor</th>
    <th>Ativo</th>
    <th></th>
  </thead>
  <tbody>
    <% @tabela_compras.each do |tabela_compra| %>
      <tr>
        <td><%= tabela_compra.data.strftime("%d/%m/%Y")  %></td>
        <td class="inline"><span class="bg-info"><%= tabela_compra.recurso.grupo_recurso.nome %></span>
         - <%= tabela_compra.recurso.nome %>-<%= tabela_compra.recurso.medida %></td>
        <td><%= tabela_compra.supplier.fantasia %></td>
        <td><%= number_to_currency(tabela_compra.valor) %></td>
        <td><%= tabela_compra.ativo==true ? "SIM" : "NÃO" %></td>
        <td> <%= link_to "Detalhes", tabela_compra, class: "btn btn-secondary" %> </td>
      </tr>
    <% end %>
  </tbody>
</div>


<script>
  $(document).ready(function(){
     $('#tabela_compras').DataTable({
        autoWidth: true,
        info: false,
        searching: true,
        order: [[1]],
        paging: false,
        "language": {
          "url": "//cdn.datatables.net/plug-ins/1.11.3/i18n/pt_br.json"
        }
     });
  });
</script>

app/views/tabela_compras/new.html.erb
<div>
    <%= link_to "Lista tabela compras", tabela_compras_path, class: "btn btn-secondary" %>
</div>

<%= render "form", tabela_compra: @tabela_compra %>
<br>
<div>
  
</div>

app/views/tabela_compras/planilha.html.erb
<div>
    <%= link_to "Lista tabela compras", tabela_compras_path, class: "btn btn-secondary" %>
</div>

<%= render "form_planilha", tabela_compra: @tabela_compra %>

app/views/tabela_compras/show.html.erb
<div id="detalhe" class="text-black">
  <h3>Tabela de Preços</h3>
  <%= render @tabela_compra %>
</div>

<div>
  <%= link_to "Edit this tabela compra", edit_tabela_compra_path(@tabela_compra), class: "btn btn-info"  %> |
  <%= link_to "Back to tabela compras", tabela_compras_path, class: "btn btn-secondary" %>

  <%= button_to "Destroy this tabela compra", @tabela_compra, method: :delete, class: "btn btn-danger" %>
</div>