config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
      get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/index'
  get 'home/about'
  
  resources :clients
  resources :grupo_recursos
  get 'tabela_compras/planilha'
  post 'tabela_compras/newPlanilha'
  resources :tabela_compras
  resources :recursos
  resources :suppliers
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/recurso.rb
# == Schema Information
#
# Table name: recursos
#
#  id               :bigint           not null, primary key
#  nome             :string
#  medida           :string
#  grupo_recurso_id :bigint           not null
#  nome_curto       :string
#  ativo            :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Recurso < ApplicationRecord
  belongs_to :grupo_recurso
  has_many :tabela_compras
  
  validates_presence_of :grupo_recurso_id, :nome, :nome_curto

  before_save :formata

  enum medidas: {'Kg':1, 'm2':2, 'mL':3, 'm3':4, 'T':5}

  def recurso_grupo
      "#{grupo_recurso.nome} - #{nome} "
  end

  private
  def formata
    self.nome = self.nome.split.collect(&:capitalize).join(' ') if self.nome && !self.nome.blank?
    self.nome_curto = self.nome_curto.split.collect(&:capitalize).join(' ') if self.nome_curto && !self.nome_curto.blank?
  end 

end

app/controllers/recursos_controller.rb
class RecursosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recurso, only: %i[ show edit update destroy ]

  # GET /recursos or /recursos.json
  def index
    @recursos = Recurso.all
    @grupo_recursos = GrupoRecurso.all
  end

  # GET /recursos/1 or /recursos/1.json
  def show
  end

  # GET /recursos/new
  def new
    @recurso = Recurso.new
  end

  # GET /recursos/1/edit
  def edit
  end

  # POST /recursos or /recursos.json
  def create
    @recurso = Recurso.new(recurso_params)

    respond_to do |format|
      if @recurso.save
        format.html { redirect_to recurso_url(@recurso), notice: "Recurso salvo com sucesso." }
        format.json { render :show, status: :created, location: @recurso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recursos/1 or /recursos/1.json
  def update
    respond_to do |format|
      if @recurso.update(recurso_params)
        format.html { redirect_to recurso_url(@recurso), notice: "Recurso atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @recurso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recursos/1 or /recursos/1.json
  def destroy
    @recurso.destroy

    respond_to do |format|
      format.html { redirect_to recursos_url, notice: "Recurso excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recurso
      @recurso = Recurso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recurso_params
      params.require(:recurso).permit(:nome, :medida, :grupo_recurso_id, :nome_curto, :ativo)
    end
end

app/helpers/recursos_helper.rb
module RecursosHelper
end

app/views/recursos/_form.html.erb
<div class="form-body">
  <div class="row">
      <div class="form-holder">
        <div class="form-content">
          <div class="form-items">
            <h3 class="form-title"> Recursos </h3>

<%= form_with(model: recurso) do |form| %>
  <% if recurso.errors.any? %>
    <div style="color: red">
      <h2><%= recurso.errors.count %> <%= recurso.errors.count==1 ? "erro deve" : "erros devem" %> ser corrigidos:</h2>

      <ul>
        <% recurso.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mt-1 mb-0">
    <%= form.label :grupo_recurso_id, "Grupo do Recurso", style: "display: block", class: "form-label"  %>
    <%= form.select :grupo_recurso_id, options_from_collection_for_select(GrupoRecurso.order(:nome), "id", "nome", recurso.grupo_recurso_id) %>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :nome, style: "display: block", class: "form-label" %>
    <%= form.text_field :nome, class: "form-control", placeholder: "Nome do recurso" %>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :medida, style: "display: block", class: "form-label"  %>
    <%= form.select :medida, options_for_select(enum_for_select(Recurso.new, :medidas), recurso.medida), {}, class: "custom-select" %>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :nome_curto, style: "display: block", class: "form-label"  %>
    <%= form.text_field :nome_curto, class: "form-control", placeholder: "Nome curto do recurso"  %>
  </div>

  <div class="mt-1 mb-0">
    <%= form.label :ativo, style: "display: block", class: "form-label"  %>
    <%= form.check_box :ativo %>
  </div>

  <div class="row" style="border-top: 4px;">
    <%= form.submit class: "btn btn-primary col-md-4 offset-md-4" %>
  </div>
<% end %>
</div>
      </div>
    </div>
  </div>
</div>

app/views/recursos/_recurso.html.erb
<div id="<%= dom_id recurso %>">
  <p>
    <strong>Nome:</strong>
    <%= recurso.nome %>
  </p>

  <p>
    <strong>Medida:</strong>
    <%= recurso.medida %>
  </p>

  <p>
    <strong>Grupo recurso:</strong>
    <%= recurso.grupo_recurso_id %>
  </p>

  <p>
    <strong>Nome curto:</strong>
    <%= recurso.nome_curto %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= recurso.ativo == true ? "SIM" : "NÃO" %>
  </p>

</div>

app/views/recursos/edit.html.erb
<%= render "form", recurso: @recurso %>
<br>

<div class="col-12">
  <%= link_to "Mostrar Recurso", @recurso, class: "btn btn-secondary"  %> |
  <%= link_to "Lista de Recursos", recursos_path, class: "btn btn-secondary"  %>
</div>

app/views/recursos/index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

<div class="flex">
  <h1 class="text-black">Recursos</h1>
  <%= link_to "+ Novo Recurso", new_recurso_path, class: "btn btn-info small" %>
</div>
<br>
<div id="tabRecursos" style="width: 98%;">
  <table id="Recursos" class="table dataTable datatable-basic table-striped table-bordered table-hover display bg-gray" 
  role="grid">
  <thead>
    <th>Grupo</th>
    <th>Nome</th>
    <th>Medida</th>
    <th>Ativo</th>
    <th></th>
  </thead>
  <tbody>
    <% @recursos.each do |recurso| %>
      <tr>
        <td><%= recurso.grupo_recurso.nome %></td>
        <td><%= recurso.nome %></td>
        <td><%= recurso.medida %></td>
        <td><%= recurso.ativo == true ? "SIM" : "NÃO" %></td>
        <td> <%= link_to "Detalhes", recurso, class: "btn btn-secondary" %> </td>
      </tr>
    <% end %>
  </tbody>
</div>


<script>
  $(document).ready(function(){
     $('#Recursos').DataTable({
        autoWidth: true,
        info: false,
        searching: true,
        order: [[1]],
        paging: false,
        "language": {
          "url": "//cdn.datatables.net/plug-ins/1.11.3/i18n/pt_br.json"
        }
     });
  });
</script>

app/views/recursos/new.html.erb
<div>
    <%= link_to "Lista de Recursos", recursos_path, class: "btn btn-secondary" %>
</div>

<%= render "form", recurso: @recurso %>
<br>

app/views/recursos/show.html.erb
<div id="detalhe" class="text-black">
  <h3>Recurso</h3>
  <%= render @recurso %>
</div>

<div class="btn-group" role="group" style="display: inline-block;">
  <%= link_to "Editar Recurso", edit_recurso_path(@recurso), class: "btn btn-info" %> |
  <%= link_to "Listar Recursos", recursos_path, class: "btn btn-secondary" %>|
  <%= button_to "Apagar este Recurso", @recurso, method: :delete, class: "btn btn-danger inline " %>
</div>